# Generated by Django 2.2.6 on 2019-11-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_sentence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
