# Generated by Django 2.2.6 on 2019-11-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191107_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sen_text',
            field=models.CharField(max_length=100),
        ),
    ]
